services:
  player:
    build: ./Player
    container_name: player-microservice
    command: uvicorn main:app --host 0.0.0.0 --port 81 --reload
    ports:
      - 81:81
    volumes:
      - ./Player:/code
  quiz:
    build: ./Quiz
    container_name: quiz-microservice
    command: uvicorn main:app --host 0.0.0.0 --port 82 --reload
    ports:
      - 82:82
    volumes:
      - ./Quiz:/code

  room:
    build: ./Room
    container_name: room-microservice
    command: uvicorn main:app --host 0.0.0.0 --port 83 --reload
    ports:
      - 83:83
    volumes:
      - ./Room:/code